apiVersion: apps\v1
kind: Deployment
metadata:
   name: mysql
   namespace: expense
   #labels of deployment resources
   labels:
     app: mysql
     tier: mysql
     project: expense
spec:
   replicas: 1
   selector:
     matchLables:
      app: mysql
      tier: mysql
      project: expense

   template:
    metadata:
      lables:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers
      - name:nginx
        image:algotsarika/mysql:1.0.0

                                            

